---
defaults: &defaults
  adapter: mysql
  username: root
  password: 
  host:     localhost

development:
  database: boothcontrol_development
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test: &test
  database: boothcontrol_test
  <<: *defaults
# production:
#   database: registrame_production
#   <<: *defaults

cucumber:
  <<: *test